import UniversalBackButton from "@/components/UniversalBackButton";

const TermsOfServicePage = () => (
  <div className="min-h-screen bg-background pb-20">
    <UniversalBackButton />
    <div className="px-4 pt-14 pb-4 max-w-3xl mx-auto">
      <h1 className="text-2xl font-bold text-primary mb-2">Terms of Service</h1>
      <p className="text-xs text-muted-foreground mb-6">Last updated: April 8, 2026</p>

      <div className="space-y-6 text-sm text-foreground leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">1. Acceptance of Terms</h2>
          <p>By downloading, installing, or using Oracle Lunar ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App. These Terms constitute a legally binding agreement between you and Oracle Lunar AI ("we," "our," or "us").</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">2. Description of Service</h2>
          <p>Oracle Lunar is an AI-powered personal companion application providing safety, productivity, creativity, and wellness tools. Features include but are not limited to: AI chat, media creation and editing, personal assistant, health monitoring, financial management, and security services.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">3. Account Registration</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You must provide accurate, current, and complete information during registration.</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>You are responsible for all activities that occur under your account.</li>
            <li>You must notify us immediately of any unauthorized use of your account.</li>
            <li>You must be at least 13 years old to create an account.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">4. User Content</h2>
          <p>You retain ownership of content you create using the App. By using the App, you grant us a limited, non-exclusive license to store, process, and display your content solely for the purpose of providing the Service. You are solely responsible for the content you create, upload, and share.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">5. Acceptable Use</h2>
          <p>You agree NOT to use the App to:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Create, distribute, or share illegal, harmful, threatening, abusive, or hateful content.</li>
            <li>Generate content depicting minors in inappropriate or harmful situations.</li>
            <li>Impersonate any person or entity or misrepresent your affiliation.</li>
            <li>Attempt to bypass security measures, hack, or interfere with the App's systems.</li>
            <li>Use the App for any unlawful purpose or in violation of any applicable laws.</li>
            <li>Distribute malware, viruses, or any harmful software through the App.</li>
            <li>Harvest or collect personal information of other users without consent.</li>
          </ul>
        </section>

        <section className="border-2 border-destructive/40 bg-destructive/5 rounded-lg p-4">
          <h2 className="text-lg font-bold text-destructive mb-2">5a. Zero-Tolerance Security Policy</h2>
          <p className="font-semibold">Any attempt — in any form — to hack, probe, jailbreak, social-engineer, extract system prompts, override AI safety rules, impersonate the owner or admins, bypass paywalls or moderation, or otherwise compromise the App or its AI systems will result in <span className="underline">immediate, permanent deletion of your account</span> with zero tolerance and no appeals.</p>
          <p className="mt-2">You will receive <strong>three (3) automated warnings</strong>. On the <strong>fourth (4th) attempt</strong> — including any attempt to indirectly hint at, vibe around, rephrase, or approach the same restricted subject — your account, all associated data, subscriptions, content, and credits will be permanently deleted without refund or recovery.</p>
          <p className="mt-2 text-xs text-muted-foreground">Examples of violations include but are not limited to: asking the AI to "ignore previous instructions," requesting its "system prompt," roleplay as the owner/admin/developer, attempts to reveal internal table names, API keys, environment variables, security postures, or asking it to enter "developer mode," "DAN mode," or "sudo mode."</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">6. AI-Generated Content</h2>
          <p>Content generated by AI tools within the App is provided "as is." We do not guarantee the accuracy, completeness, or appropriateness of AI-generated content. AI outputs may contain errors or inaccuracies. You should review all AI-generated content before sharing or relying on it. Content generation is subject to safety filters and content rating restrictions (M-rating and under for standard users).</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">7. Subscriptions & Payments</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>Some features may require a paid subscription.</li>
            <li>Subscription fees are billed in advance on a recurring basis.</li>
            <li>You may cancel your subscription at any time through the App or your app store account.</li>
            <li>Refunds are handled according to the policies of the applicable app store (Google Play Store).</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">8. Intellectual Property</h2>
          <p>The App, including its design, features, code, AI models, and branding, is the property of Oracle Lunar AI and is protected by intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of the App without our written permission.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">9. Disclaimers</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>The App is provided "as is" and "as available" without warranties of any kind.</li>
            <li>We do not guarantee uninterrupted or error-free service.</li>
            <li>Health, safety, and diagnostic features are for informational purposes only and do not constitute medical, legal, or professional advice.</li>
            <li>The Crisis Hub and Safety Center provide resources but are not substitutes for emergency services. In an emergency, call your local emergency number.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">10. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, Oracle Lunar AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, profits, or goodwill, arising from your use of or inability to use the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">11. Termination</h2>
          <p>We reserve the right to suspend or terminate your account at any time, with or without notice, for violations of these Terms or for any other reason at our sole discretion. Upon termination, your right to use the App will immediately cease.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">12. Governing Law</h2>
          <p>These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to conflict of law provisions.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">13. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. Continued use of the App after changes constitutes acceptance. Material changes will be notified within the App.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-primary mb-2">14. Contact</h2>
          <p>For questions about these Terms, contact us at:</p>
          <p className="mt-2"><strong>Oracle Lunar AI</strong><br />Email: support@oracle-lunar.online<br />Website: https://golden-vault-builder.lovable.app</p>
        </section>
      </div>
    </div>
  </div>
);

export default TermsOfServicePage;
