import { useMemo, useState } from "react";
import { Globe, Smartphone, Rocket, Download, RefreshCw, FileText, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { useNavigate } from "react-router-dom";
import solaceLogo from "@/assets/solace-logo.png";
import { MASTER_AI_AVATAR as aiAvatar } from "@/assets/master-ai-avatar";
import { useSaveMedia } from "@/hooks/useUserAvatars";

const STEPS = [
  "⚙ Scanning URL structure...",
  "📄 Generating AndroidManifest.xml...",
  "📱 Creating WebView Activity...",
  "⚡ Configuring build.gradle...",
  "🔑 Signing keystore template...",
  "✓ Packaging APK wrapper project...",
];

const buildPackageId = (url: string, appName: string) => {
  const host = url.replace(/https?:\/\//, "").split("/")[0].replace(/[^a-z0-9.]/gi, "").toLowerCase();
  const parts = host.split(".").filter(Boolean);
  const domain = parts.length >= 2 ? parts[parts.length - 2] : "mysite";
  const name = appName.replace(/\s+/g, "").replace(/[^a-z0-9]/gi, "").toLowerCase() || "myapp";
  return `com.${domain}.${name}`;
};

const buildWrapperContent = (url: string, appName: string, pkg: string) => [
  "SOLACE PORTAL — WEBSITE → PLAY STORE WRAPPER",
  "═══════════════════════════════════════════════",
  "Generated: " + new Date().toLocaleString(),
  "",
  "APP DETAILS",
  "  App Name  : " + appName,
  "  Website   : " + url,
  "  Package ID: " + pkg,
  "  Min SDK   : 21 (Android 5.0+)",
  "  Target SDK: 34 (Android 14)",
  "",
  "PROJECT STRUCTURE",
  "  app/src/main/AndroidManifest.xml",
  "  app/src/main/java/" + pkg.replace(/\./g, "/") + "/MainActivity.java",
  "  app/src/main/res/layout/activity_main.xml",
  "  app/build.gradle",
  "  build.gradle",
  "",
  "MainActivity.java",
  "─────────────────",
  "package " + pkg + ";",
  "import android.webkit.*;",
  "import android.os.Bundle;",
  "import androidx.appcompat.app.AppCompatActivity;",
  "public class MainActivity extends AppCompatActivity {",
  "  @Override protected void onCreate(Bundle b){",
  "    super.onCreate(b);",
  "    WebView wv = new WebView(this);",
  "    setContentView(wv);",
  "    wv.getSettings().setJavaScriptEnabled(true);",
  "    wv.getSettings().setDomStorageEnabled(true);",
  "    wv.setWebViewClient(new WebViewClient());",
  '    wv.loadUrl("' + url + '");',
  "  }",
  "}",
  "",
  "AndroidManifest.xml",
  "────────────────────",
  '<manifest xmlns:android="http://schemas.android.com/apk/res/android"',
  '  package="' + pkg + '">',
  '  <uses-permission android:name="android.permission.INTERNET"/>',
  '  <application android:label="' + appName + '"',
  '    android:theme="@style/Theme.AppCompat.NoActionBar">',
  '    <activity android:name=".MainActivity"',
  '      android:exported="true">',
  "      <intent-filter>",
  '        <action android:name="android.intent.action.MAIN"/>',
  '        <category android:name="android.intent.category.LAUNCHER"/>',
  "      </intent-filter>",
  "    </activity>",
  "  </application>",
  "</manifest>",
  "",
  "NEXT STEPS — UPLOAD TO PLAY STORE",
  "1. Open Android Studio and import this project",
  "2. Build → Generate Signed Bundle/APK",
  "3. Create keystore (first time) or use existing",
  "4. Select AAB format (required by Play Store)",
  "5. Go to https://play.google.com/console",
  "6. Create App → Upload AAB → Complete store listing → Publish",
  "",
  "DIRECT LINK TO PLAY CONSOLE:",
  "https://play.google.com/console/u/0/developers",
  "",
  "─── Generated by Solace Portal AI Suite ───",
].join("\n");

const downloadFile = (filename: string, content: string) => {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const WebWrapperPage = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const saveMedia = useSaveMedia();
  // Pre-fill from query params: /web-wrapper?url=...&name=...
  const params = new URLSearchParams(typeof window !== "undefined" ? window.location.search : "");
  const [url, setUrl] = useState(params.get("url") || "");
  const [appName, setAppName] = useState(params.get("name") || "");
  const [progress, setProgress] = useState(0);
  const [statusText, setStatusText] = useState(STEPS[0]);
  const [working, setWorking] = useState(false);
  const [done, setDone] = useState(false);

  const pkgId = useMemo(() => buildPackageId(url, appName), [url, appName]);

  const wrap = () => {
    if (!url || !url.startsWith("http")) {
      toast({ title: "Invalid URL", description: "Please enter a valid https:// URL.", variant: "destructive" });
      return;
    }
    if (!appName.trim()) {
      toast({ title: "App name required", description: "Please enter your app name.", variant: "destructive" });
      return;
    }
    setWorking(true);
    setDone(false);
    setProgress(0);
    let step = 0;
    const tick = setInterval(() => {
      step += 1;
      const pct = Math.min((step / STEPS.length) * 100, 100);
      setProgress(pct);
      if (step <= STEPS.length) setStatusText(STEPS[step - 1]);
      if (step >= STEPS.length) {
        clearInterval(tick);
        const safeName = appName.trim().replace(/\s+/g, "_");
        const content = buildWrapperContent(url.trim(), appName.trim(), pkgId);
        downloadFile(`${safeName}_play_store_wrapper.txt`, content);
        setDone(true);
        setWorking(false);
        toast({ title: "Wrapper generated", description: "Play Store wrapper package downloaded & saved to your library." });
        // Auto-save wrapper to library
        try {
          const dataUrl = `data:text/plain;charset=utf-8,${encodeURIComponent(content)}`;
          void saveMedia.mutateAsync({
            media_type: "text",
            title: `${appName.trim()} — Play Store Wrapper`,
            url: dataUrl,
            source_page: "apps",
            metadata: { url: url.trim(), package_id: pkgId, app_name: appName.trim(), kind: "wrapper" },
          });
        } catch { /* non-blocking */ }
      }
    }, 280);
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Top bar */}
      <header className="sticky top-0 z-40 backdrop-blur-md bg-background/70 border-b border-border">
        <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between">
          <button onClick={() => navigate("/")} className="flex items-center gap-2 hover:opacity-80 transition-opacity">
            <img src={solaceLogo} alt="SOLACE" className="h-8 w-8 drop-shadow-[0_0_10px_hsl(var(--primary)/0.6)]" />
            <span className="font-bold tracking-[0.2em] text-primary">SOLACE</span>
          </button>
          <Button variant="ghost" size="sm" onClick={() => navigate("/")}>
            <ArrowLeft className="mr-1 h-4 w-4" /> Back to portal
          </Button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-10">
        <div className="text-center mb-10">
          {/* SOLACE AI guide avatar */}
          <div className="flex justify-center mb-4">
            <div className="relative">
              <div className="absolute inset-0 rounded-full bg-primary/30 blur-xl animate-pulse" />
              <img
                src={aiAvatar}
                alt="SOLACE AI Wrapper Assistant"
                className="relative h-24 w-24 rounded-full object-cover border-2 border-primary shadow-[0_0_30px_hsl(var(--primary)/0.6)]"
              />
              <span className="absolute bottom-0 right-0 h-4 w-4 rounded-full bg-primary border-2 border-background shadow-[0_0_10px_hsl(var(--primary))]" />
            </div>
          </div>
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-card/80 backdrop-blur px-4 py-1.5 text-xs text-muted-foreground mb-4">
            <Globe className="h-3.5 w-3.5 text-primary" />
            Your AI Wrapper Assistant — URL → APK → Play Store
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-3">
            <span className="text-primary drop-shadow-[0_0_20px_hsl(var(--primary)/0.5)]">Web Wrapper</span>
          </h1>
          <p className="text-muted-foreground max-w-xl mx-auto">
            Turn any website into a native Android app, ready to upload to Google Play.
          </p>
        </div>

        {/* How it works */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-8">
          {[
            { icon: Globe, title: "1. Enter URL", desc: "Your website or web app https://" },
            { icon: Smartphone, title: "2. Wrap It", desc: "We wrap it as a native Android APK" },
            { icon: Rocket, title: "3. Upload", desc: "Submit straight to Play Console" },
          ].map(({ icon: Icon, title, desc }) => (
            <div key={title} className="holo-tile rounded-xl p-4 text-center">
              <Icon className="holo-icon h-7 w-7 text-primary mx-auto mb-2" />
              <div className="font-semibold text-sm text-foreground">{title}</div>
              <div className="text-xs text-muted-foreground mt-1">{desc}</div>
            </div>
          ))}
        </div>

        {/* Form */}
        <div className="holo-tile rounded-2xl p-6 space-y-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="wrap-url" className="text-xs uppercase tracking-wider text-muted-foreground">Your website URL</Label>
              <Input
                id="wrap-url"
                type="url"
                placeholder="https://yoursite.com"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="wrap-name" className="text-xs uppercase tracking-wider text-muted-foreground">App name</Label>
              <Input
                id="wrap-name"
                type="text"
                placeholder="My App"
                value={appName}
                onChange={(e) => setAppName(e.target.value)}
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label className="text-xs uppercase tracking-wider text-muted-foreground">Package ID (auto-filled)</Label>
            <Input value={pkgId} readOnly className="font-mono text-sm bg-muted/40" />
          </div>

          {working && (
            <div className="space-y-2">
              <div className="text-xs text-primary font-semibold">{statusText}</div>
              <div className="h-2 rounded-full bg-muted overflow-hidden">
                <div
                  className="h-full bg-primary transition-all duration-300 shadow-[0_0_12px_hsl(var(--primary))]"
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>
          )}

          {done && (
            <div className="rounded-xl border border-primary/30 bg-primary/5 p-4">
              <div className="font-semibold text-primary mb-1 flex items-center gap-2">
                <FileText className="h-4 w-4" /> APK Wrapper Package Generated!
              </div>
              <p className="text-sm text-muted-foreground mb-3">
                Your WebView APK project has been generated and downloaded. Now upload your AAB file to Play Console to publish.
              </p>
              <div className="flex flex-wrap gap-2">
                <Button onClick={() => window.open("https://play.google.com/console/u/0/developers", "_blank")}>
                  <Rocket className="mr-2 h-4 w-4" /> Open Play Console
                </Button>
                <Button variant="outline" onClick={wrap}>
                  <RefreshCw className="mr-2 h-4 w-4" /> Re-wrap
                </Button>
              </div>
              <p className="text-xs text-muted-foreground mt-3">
                <strong>How to submit:</strong> Play Console → Create App → Upload AAB → Store Listing → Publish
              </p>
            </div>
          )}

          <div className="flex flex-wrap gap-2 pt-2">
            <Button
              onClick={wrap}
              disabled={working}
              size="lg"
              className="shadow-[0_0_30px_hsl(var(--primary)/0.4)]"
            >
              <Download className="mr-2 h-4 w-4" />
              {working ? "Wrapping..." : "Wrap for Play Store"}
            </Button>
            <Button variant="outline" onClick={() => window.open("https://play.google.com/console/u/0/developers", "_blank")}>
              Play Console
            </Button>
            <Button variant="ghost" onClick={() => window.open("https://developer.android.com/studio/publish", "_blank")}>
              Publish Guide
            </Button>
          </div>
        </div>

        <p className="text-xs text-muted-foreground text-center mt-6">
          The downloaded file contains the AndroidManifest, MainActivity Java source, and step-by-step Play Store submission instructions.
        </p>
      </main>
    </div>
  );
};

export default WebWrapperPage;
