// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Oracle Lunar user (id and email) for the current MCP session.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const payload = { user_id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-diary-entries.ts
import { createClient } from "npm:@supabase/supabase-js@2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function userClient(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_diary_entries_default = defineTool2({
  name: "list_diary_entries",
  title: "List diary entries",
  description: "List the signed-in user's Life Diary entries, most recent first. RLS restricts results to this user only.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await userClient(ctx).from("diary_entries").select("id, entry_date, title, content, mood, tags, category, created_at").order("entry_date", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-diary-entry.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function userClient2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_diary_entry_default = defineTool3({
  name: "create_diary_entry",
  title: "Create diary entry",
  description: "Create a new Life Diary entry for the signed-in user.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Short title for the entry."),
    content: z2.string().trim().min(1).describe("Body text of the diary entry."),
    mood: z2.string().trim().optional().describe("Optional mood label, e.g. 'calm', 'grateful'."),
    entry_date: z2.string().optional().describe("YYYY-MM-DD date. Defaults to today."),
    tags: z2.array(z2.string()).optional(),
    category: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const row = {
      user_id: ctx.getUserId(),
      title: input.title,
      content: input.content,
      mood: input.mood ?? null,
      entry_date: input.entry_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      tags: input.tags ?? null,
      category: input.category ?? null
    };
    const { data, error } = await userClient2(ctx).from("diary_entries").insert(row).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created diary entry ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/get-wallet-balance.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function userClient3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_wallet_balance_default = defineTool4({
  name: "get_wallet_balance",
  title: "Get wallet balance",
  description: "Return the signed-in user's Oracle Lunar wallet balance (cents) and currency.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const { data, error } = await userClient3(ctx).from("wallet_balances").select("balance_cents, currency, updated_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = data ?? { balance_cents: 0, currency: "USD", updated_at: null };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-calendar-events.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function userClient4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_calendar_events_default = defineTool5({
  name: "list_calendar_events",
  title: "List calendar events",
  description: "List the signed-in user's upcoming calendar events, sorted by date.",
  inputSchema: {
    from_date: z3.string().optional().describe("Inclusive YYYY-MM-DD start date. Defaults to today."),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const start = from_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await userClient4(ctx).from("calendar_events").select("id, title, description, event_date, start_time, end_time, category").gte("event_date", start).order("event_date", { ascending: true }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tpkpfkcnqdyrzpqdoqnp";
var mcp_default = defineMcp({
  name: "oracle-lunar-mcp",
  title: "Oracle Lunar",
  version: "0.1.0",
  instructions: "Tools for the signed-in Oracle Lunar user. Read and write their Life Diary, view calendar events, and check their wallet balance. All tools run as the connected user under RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_diary_entries_default,
    create_diary_entry_default,
    get_wallet_balance_default,
    list_calendar_events_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
