// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/lib/errors.ts
function mcpError(code, message, details) {
  const payload = { code, message, ...details ? { details } : {} };
  return {
    content: [{ type: "text", text: JSON.stringify({ error: payload }) }],
    structuredContent: { error: payload },
    isError: true
  };
}
function mcpOk(structured, humanText) {
  return {
    content: [{ type: "text", text: humanText ?? JSON.stringify(structured) }],
    structuredContent: structured
  };
}
var notAuthenticated = () => mcpError(
  "unauthenticated",
  "Not signed in. Reconnect the Oracle Lunar MCP server and complete the sign-in and consent flow."
);
function fromPostgrestError(err) {
  const code = err.code ?? "";
  if (code === "42501" || /row-level security|permission denied/i.test(err.message)) {
    return mcpError(
      "forbidden",
      "Access denied by row-level security. This tool can only read or modify data that belongs to the signed-in user.",
      { pgCode: code }
    );
  }
  if (code === "PGRST116") {
    return mcpError("not_found", "No matching record found for the signed-in user.", { pgCode: code });
  }
  if (code === "23505") {
    return mcpError("conflict", "That record already exists.", { pgCode: code });
  }
  if (code === "23503" || code === "23514" || code === "23502") {
    return mcpError("invalid_input", err.message, { pgCode: code });
  }
  if (/rate.?limit|too many/i.test(err.message)) {
    return mcpError("rate_limited", "The backend is rate-limiting requests. Try again shortly.");
  }
  return mcpError("internal", err.message || "Unexpected database error.", { pgCode: code });
}
function fromUnknown(err) {
  const message = err instanceof Error ? err.message : String(err);
  return mcpError("internal", message);
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Oracle Lunar user (id and email) for the current MCP session.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    return mcpOk({ user_id: ctx.getUserId(), email: ctx.getUserEmail() });
  }
});

// src/lib/mcp/tools/list-diary-entries.ts
import { createClient } from "npm:@supabase/supabase-js@^2.117.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.6.5";
function userClient(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_diary_entries_default = defineTool2({
  name: "list_diary_entries",
  title: "List diary entries",
  description: "List the signed-in user's Life Diary entries, most recent first. RLS restricts results to this user only.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    try {
      const { data, error } = await userClient(ctx).from("diary_entries").select("id, entry_date, title, content, mood, tags, category, created_at").order("entry_date", { ascending: false }).limit(limit);
      if (error) return fromPostgrestError(error);
      return mcpOk({ entries: data ?? [] });
    } catch (err) {
      return fromUnknown(err);
    }
  }
});

// src/lib/mcp/tools/create-diary-entry.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.117.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.6.5";
function userClient2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
var create_diary_entry_default = defineTool3({
  name: "create_diary_entry",
  title: "Create diary entry",
  description: "Create a new Life Diary entry for the signed-in user.",
  inputSchema: {
    title: z2.string().trim().min(1).describe("Short title for the entry."),
    content: z2.string().trim().min(1).describe("Body text of the diary entry."),
    mood: z2.string().trim().optional().describe("Optional mood label, e.g. 'calm', 'grateful'."),
    entry_date: z2.string().optional().describe("YYYY-MM-DD date. Defaults to today."),
    tags: z2.array(z2.string()).optional(),
    category: z2.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (input.entry_date && !DATE_RE.test(input.entry_date)) {
      return mcpError("invalid_input", "entry_date must be an ISO date in YYYY-MM-DD format.");
    }
    try {
      const row = {
        user_id: ctx.getUserId(),
        title: input.title,
        content: input.content,
        mood: input.mood ?? null,
        entry_date: input.entry_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
        tags: input.tags ?? null,
        category: input.category ?? null
      };
      const { data, error } = await userClient2(ctx).from("diary_entries").insert(row).select().single();
      if (error) return fromPostgrestError(error);
      return mcpOk({ entry: data }, `Created diary entry ${data.id}`);
    } catch (err) {
      return fromUnknown(err);
    }
  }
});

// src/lib/mcp/tools/get-wallet-balance.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.117.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function userClient3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_wallet_balance_default = defineTool4({
  name: "get_wallet_balance",
  title: "Get wallet balance",
  description: "Return the signed-in user's Oracle Lunar wallet balance (cents) and currency.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    try {
      const { data, error } = await userClient3(ctx).from("wallet_balances").select("balance_cents, currency, updated_at").maybeSingle();
      if (error) return fromPostgrestError(error);
      const payload = data ?? { balance_cents: 0, currency: "USD", updated_at: null };
      return mcpOk(payload);
    } catch (err) {
      return fromUnknown(err);
    }
  }
});

// src/lib/mcp/tools/list-calendar-events.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.117.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.6.5";
function userClient4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var DATE_RE2 = /^\d{4}-\d{2}-\d{2}$/;
var list_calendar_events_default = defineTool5({
  name: "list_calendar_events",
  title: "List calendar events",
  description: "List the signed-in user's upcoming calendar events, sorted by date.",
  inputSchema: {
    from_date: z3.string().optional().describe("Inclusive YYYY-MM-DD start date. Defaults to today."),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (from_date && !DATE_RE2.test(from_date)) {
      return mcpError("invalid_input", "from_date must be an ISO date in YYYY-MM-DD format.");
    }
    try {
      const start = from_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
      const { data, error } = await userClient4(ctx).from("calendar_events").select("id, title, description, event_date, start_time, end_time, category").gte("event_date", start).order("event_date", { ascending: true }).limit(limit);
      if (error) return fromPostgrestError(error);
      return mcpOk({ events: data ?? [] });
    } catch (err) {
      return fromUnknown(err);
    }
  }
});

// src/lib/mcp/tools/books.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.117.2";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.6.5";
function userClient5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var words = (s) => s.trim() ? s.trim().split(/\s+/).length : 0;
async function loadDoc(ctx, bookId) {
  const { data, error } = await userClient5(ctx).rpc("get_story_writer_document", { _story_id: bookId });
  if (error) throw error;
  const { id: _id, ...doc } = data ?? {};
  return { title: doc.title ?? "", metadata: doc, chapters: doc.chapters ?? [] };
}
var listBooksTool = defineTool6({
  name: "list_books",
  title: "List my books",
  description: "List the signed-in user's Story Writer books with id, title, chapter count and word count.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_a, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    try {
      const { data, error } = await userClient5(ctx).from("user_media").select("id, title, metadata, updated_at").eq("user_id", ctx.getUserId()).eq("media_type", "story").order("updated_at", { ascending: false }).limit(50);
      if (error) return fromPostgrestError(error);
      const books = (data ?? []).map((r) => {
        const ch = r.metadata?.chapters ?? [];
        return {
          id: r.id,
          title: r.title ?? "Untitled",
          chapters: ch.length,
          words: ch.reduce((n, c) => n + words(c.content ?? ""), 0),
          updated_at: r.updated_at
        };
      });
      return mcpOk({ books });
    } catch (err) {
      return fromUnknown(err);
    }
  }
});
var getBookChaptersTool = defineTool6({
  name: "get_book_chapters",
  title: "Read book chapters",
  description: "Read the full text of a range of chapters (1-based, up to 5 at a time) from one of the user's books.",
  inputSchema: {
    book_id: z4.string().uuid().describe("Book id from list_books."),
    from_chapter: z4.number().int().min(1).default(1).describe("First chapter number."),
    count: z4.number().int().min(1).max(5).default(3).describe("How many chapters to return (max 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ book_id, from_chapter, count }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    try {
      const doc = await loadDoc(ctx, book_id);
      const slice = doc.chapters.slice(from_chapter - 1, from_chapter - 1 + count).map((c, i) => ({
        number: from_chapter + i,
        title: c.title ?? "",
        words: words(c.content ?? ""),
        content: c.content ?? ""
      }));
      return mcpOk({ book_title: doc.title, total_chapters: doc.chapters.length, chapters: slice });
    } catch (err) {
      return fromUnknown(err);
    }
  }
});
var saveBookChapterTool = defineTool6({
  name: "save_book_chapter",
  title: "Save a book chapter",
  description: "Replace an existing chapter's title and text, or add a new chapter at the end (chapter_number = total + 1). Existing pictures on that chapter are kept.",
  inputSchema: {
    book_id: z4.string().uuid().describe("Book id from list_books."),
    chapter_number: z4.number().int().min(1).describe("Chapter to replace, or total+1 to add a new one."),
    title: z4.string().trim().min(1).max(200).describe("Chapter title."),
    content: z4.string().trim().min(50).describe("Full chapter text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ book_id, chapter_number, title, content }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    try {
      const { data, error } = await userClient5(ctx).rpc("save_story_chapter_text", {
        _story_id: book_id,
        _chapter_number: chapter_number,
        _title: title,
        _content: content
      });
      if (error) {
        if (/use \d+ to add a new one/.test(error.message)) return mcpOk({ saved: false, message: error.message });
        return fromPostgrestError(error);
      }
      return mcpOk({ saved: true, chapter_number, words: words(content), total_chapters: Number(data) });
    } catch (err) {
      return fromUnknown(err);
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "tpkpfkcnqdyrzpqdoqnp";
var mcp_default = defineMcp({
  name: "oracle-lunar-mcp",
  title: "Oracle Lunar",
  version: "0.2.0",
  instructions: "Tools for the signed-in Oracle Lunar user. Read and write their Life Diary, view calendar events, check their wallet balance, and read/write their Story Writer books (list_books, get_book_chapters, save_book_chapter \u2014 read chapters in small batches). All tools run as the connected user under RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_diary_entries_default,
    create_diary_entry_default,
    get_wallet_balance_default,
    list_calendar_events_default,
    listBooksTool,
    getBookChaptersTool,
    saveBookChapterTool
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
